// Generated by CoffeeScript 1.11.1
app.controller('Index', [
  '$scope', '$rootScope', function($scope, $rootScope) {
    $scope.myDirectory = myDirectoryI.directory;
    return $rootScope.showBanner = true;
  }
]);
