// Generated by CoffeeScript 1.11.1

/*
 * Created by Iacuzzo Giovanni
 */
(function() {
  'use-strict';

  /*
   * @module {customContact}
   */
  var cContact;
  cContact = angular.module('customContact', ['angular-click-outside']);
  cContact.controller('contactController', [
    '$scope', 'Contact', function($scope, Contact) {
      var contact;
      contact = this;
      contact.isOpen = false;
      Contact.get().then(function(d) {
        contact.data = d;
        console.log(contact.data.page);
      });
      contact.onOpen = function() {
        if (contact.isOpen === false) {
          return contact.isOpen = true;
        }
      };
      contact.onClose = function() {
        if (contact.isOpen === true) {
          return contact.isOpen = false;
        }
      };
    }
  ]);
  cContact.directive('contactModal', [
    function() {
      return {
        restrict: 'E',
        replace: true,
        templateUrl: myLocalized.partials + 'contact.html',
        controller: 'contactController',
        controllerAs: 'contact',
        link: function(scope, element, attrs, contact) {
          contact.modalDialog = element[0];
        }
      };
    }
  ]);
  cContact.directive('contactNavLink', [
    function() {
      return {
        restrict: 'E',
        require: '^?contactModal',
        templateUrl: myLocalized.partials + 'contact-nav-link.html',
        link: function(scope, element, attrs) {
          console.log('contactNavLink Loaded');
        }
      };
    }
  ]);
})();
